name: My First GitHub Action
on: [push] # It ll run on when we push to git
jobs: # Jobs may not run sequencially
  build-app:
    runs-on: ubuntu-latest
    steps: # Step ll run sequentially
      - uses: actions/checkout@v2 # This clones the repo to the GitHub Runner
      - uses: actions/setup-node@v2 # Setup node
        # with:
        #   node-version: '14.17.0'
      - name: Install node_modules
        run: yarn
      - name: Build the Project
        run: yarn build
      - name: Deploying the project
        env:
          VERCEL_ORG_ID: j4RgRgNn9kctl8epQ92dcBW8
          VERCEL_PROJECT_ID: prj_FNHwAR4NxV8bHcNc1qrDjtcSqkk7
        run: yarn deploy
      - name: Setup Finish
        run: echo "Hurray!"
  
